//
//  InvestimentViewController.swift
//  FinacialApp
//
//  Created by Thiago Souza on 17/05/20.
//  Copyright (c) 2020 Thiago Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentDisplayLogic: class
{
  func displayInitialData(viewModel: Investiment.Something.ViewModel)
}

class InvestimentViewController: UIViewController, InvestimentDisplayLogic
{
  var interactor: InvestimentBusinessLogic?
  var router: (NSObjectProtocol & InvestimentRoutingLogic & InvestimentDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = InvestimentInteractor()
    let presenter = InvestimentPresenter()
    let router = InvestimentRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
    view.backgroundColor = .magenta
    NetWorkManager().getScreen { (screen) in
        print(screen)
    }
    
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Investiment.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displayInitialData(viewModel: Investiment.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
