//
//  InvestimentPresenter.swift
//  FinacialApp
//
//  Created by Thiago Souza on 17/05/20.
//  Copyright (c) 2020 Thiago Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvestimentPresentationLogic
{
  func presentSomething(response: Investiment.Something.Response)
}

class InvestimentPresenter: InvestimentPresentationLogic
{
  weak var viewController: InvestimentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Investiment.Something.Response)
  {
    let viewModel = Investiment.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
