//
//  ContactInteractor.swift
//  FinacialApp
//
//  Created by Thiago Souza on 17/05/20.
//  Copyright (c) 2020 Thiago Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactBusinessLogic
{
  func doLoadInitialData(request: Contact.Load.Request)
}

protocol ContactDataStore
{
  //var name: String { get set }
}

class ContactInteractor: ContactBusinessLogic, ContactDataStore
{
  var presenter: ContactPresentationLogic?
  var worker: ContactWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doLoadInitialData(request: Contact.Load.Request)
  {
    worker = ContactWorker()
    worker?.fetchCells(completionHandler: { (cells) in
        let response  = Contact.Load.Response(cells: cells)
        self.presenter?.presentInitialData(response: response)
    })
//    worker?.doSomeWork()
//
//    let response = Contact.Load.Response(cells: request)
//    presenter?.presentSomething(response: response)
  }
}
