//
//  ContactPresenter.swift
//  FinacialApp
//
//  Created by Thiago Souza on 17/05/20.
//  Copyright (c) 2020 Thiago Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactPresentationLogic
{
  func presentInitialData(response: Contact.Load.Response)
}

class ContactPresenter: ContactPresentationLogic
{
  weak var viewController: ContactDisplayLogic?
  
  // MARK: Do something
  
  func presentInitialData(response: Contact.Load.Response)
  {
    let viewModel = Contact.Load.ViewModel(cells: response.cells)
    viewController?.displayInitialData(viewModel: viewModel)
  }
}
